name: Node.js Package

on:
  release:
    types: [created]

jobs: 
  publish-npm:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12      
      - run: echo ::set-env name=TAG::$(echo ${GITHUB_REF} |tr -d "refs/tags")
      - run: sed -i "s/version.*/version\":\"${TAG}\",/" package.json
      - run: npm ci
      - name: Authenticate to npm
        run: echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET }}    
      - run: npm publish
