name: Node.js Package

on:
  release:
    types: [edited, published, created]

jobs: 
  publish-npm:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/lechen26
      - run: | 
         echo ::set-env name=TAG::$(echo ${GITHUB_REF} |tr -d "refs/tags")   
      - run: sed -i "s/version.*/version\":\"${TAG}\",/" package.json   
      - run: npm ci
      - name: Create .npmrc
        run: echo "//registry.npmjs.org/lechen26:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_SECRET }}
      - run: npm publish --access public        
