name: Node.js Package

on:
  release:
    types: [edited, published, created]

jobs: 
  publish-npm:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/lechen26
      - run: TAG=`echo ${GITHUB_REF} |tr -d "refs/tags"`
      - run: sed -i "s/version:.*/version:\"${TAG}\"/" package.json
      - run: cat package.json  
      - run: sed -i 's/version.*/version:"1.2.3"/' package.json
      - run: cat package.json    
      - run: npm ci
      - run: npm publish --registry=https://registry.npmjs.org/ --tag ver --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_SECRET}}  
