name: Node.js Package

on:
  release:
    types: [created]

jobs: 
  publish-npm:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - run: echo ::set-env name=TAG::$(echo ${GITHUB_REF} |tr -d "refs/tags")
      - run: sed -i "s/version.*/version\":\"${TAG}\",/" package.json
      - run: npm ci
      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_SECRET }}" >> ~/.npmrc
      - run: npm publish
